### index method - current user enquiries
GET http://localhost:3000/api/enquiries
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY5MTY5NTMsInN1YiI6MX0.M_IN2WSXLVaJ4Wrc-47QtS175Bo_FQ6edjUFhNsRk9M

### Creating an enquiry - Success 
POST http://localhost:3000/api/enquiries
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY5MTI0MDIsInN1YiI6MX0.RFDdsn087pgvKoYq1vZx8iPKWpN85WAvg9RhH-NQvws

{
    "name":"Test3",
    "contact": "0411123123",
    "topic_id": 3,
    "message":"message test"
}

### Creating an enquiry - fail 
POST http://localhost:3000/api/enquiries
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY4ODQyNTMsInN1YiI6MX0.ktkruy4A40A31CkrGFCjcAuIdS3nGK59V7NztiO_o2A

{
    "name":"hi",
    "contact": 1234,
    "message":"hello"
}

### Show enquiry - success 
GET http://localhost:3000/api/enquiries/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY4ODQyNTMsInN1YiI6MX0.ktkruy4A40A31CkrGFCjcAuIdS3nGK59V7NztiO_o2A

### Show enquiry - fail 
GET http://localhost:3000/api/enquiries/2000
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY4ODQyNTMsInN1YiI6MX0.ktkruy4A40A31CkrGFCjcAuIdS3nGK59V7NztiO_o2A

### Update enquiry
PUT http://localhost:3000/api/enquiries/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY5MTc2OTMsInN1YiI6MX0.20YATHVzO6uaJhy7cVRyjbV1L4H-xN_4Bjx0hojNuV8

{
    "name":"bob-update",
    "contact": "1235",
    "topic_id": 2,
    "message":"this is a test message 2"
}

### Delete method
DELETE http://localhost:3000/api/enquiries/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY5MTc2OTMsInN1YiI6MX0.20YATHVzO6uaJhy7cVRyjbV1L4H-xN_4Bjx0hojNuV8

### Registarion method
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "username": "username",
    "first_name": "first",
    "middle_name": "middle",
    "last_name": "last", 
    "email": "email",
    "password": "password1",
    "password_confirmation": "password1"
}

### Sign in user
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{ 
    "email": "test@test.com",
    "password": "password"
}

### Sign in user - incorrect details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{ 
    "email": "test123",
    "password": "passwo"
}

### Update user details 

### Delete user details 

### Admin method - view all users 


### get topics 
GET http://localhost:3000/api/topics

### get cakes
GET http://localhost:3000/api/cakes

### show cakes
GET http://localhost:3000/api/cakes/1

