
## LIVE SITE HTTP REQUESTS 

### Sign in user
POST https://sprinkles-of-joy-api.herokuapp.com/api/auth/sign_in
Content-Type: application/json

{ 
    "email": "test@test.com",
    "password": "password"
}

### Sign in user admin
POST https://sprinkles-of-joy-api.herokuapp.com/api/auth/sign_in
Content-Type: application/json

{ 
    "email": "admin@admin.com",
    "password": "password"
}


### Sign in user - incorrect details
POST https://sprinkles-of-joy-api.herokuapp.com/api/auth/sign_in
Content-Type: application/json

{ 
    "email": "test123",
    "password": "passwo"
}

### Registarion method
POST https://sprinkles-of-joy-api.herokuapp.com/api/auth/sign_up
Content-Type: application/json

{
    "username": "username2",
    "first_name": "first",
    "middle_name": "middle",
    "last_name": "last", 
    "email": "email3@email.com",
    "password": "password1",
    "password_confirmation": "password1",
    "admin": "false"
}

### Registarion method -fail (taken & wrong password) 
POST https://sprinkles-of-joy-api.herokuapp.com/api/auth/sign_up
Content-Type: application/json

{
    "username": "username",
    "first_name": "first",
    "middle_name": "middle",
    "last_name": "last", 
    "email": "email@email.com",
    "password": "password1",
    "password_confirmation": "password"
}

### get topics 
GET https://sprinkles-of-joy-api.herokuapp.com/api/topics

### get cakes
GET https://sprinkles-of-joy-api.herokuapp.com/api/cakes

### show cake
GET https://sprinkles-of-joy-api.herokuapp.com/api/cakes/1

### Index method - show all current user enquiries
GET https://sprinkles-of-joy-api.herokuapp.com/api/enquiries
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY5MTY5NTMsInN1YiI6MX0.M_IN2WSXLVaJ4Wrc-47QtS175Bo_FQ6edjUFhNsRk9M

### Creating an enquiry - Success 
POST https://sprinkles-of-joy-api.herokuapp.com/api/enquiries
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY5MTI0MDIsInN1YiI6MX0.RFDdsn087pgvKoYq1vZx8iPKWpN85WAvg9RhH-NQvws

{
    "name":"Test3",
    "contact": "0411123123",
    "topic_id": 3,
    "message":"message test"
}

### Creating an enquiry - fail 
POST https://sprinkles-of-joy-api.herokuapp.com/api/enquiries
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY4ODQyNTMsInN1YiI6MX0.ktkruy4A40A31CkrGFCjcAuIdS3nGK59V7NztiO_o2A

{
    "name":"hi",
    "contact": 1234,
    "message":"hello"
}

### Show enquiry - success 
GET https://sprinkles-of-joy-api.herokuapp.com/api/enquiries/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY4ODQyNTMsInN1YiI6MX0.ktkruy4A40A31CkrGFCjcAuIdS3nGK59V7NztiO_o2A

### Show enquiry - fail 
GET https://sprinkles-of-joy-api.herokuapp.com/api/enquiries/2000
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY4ODQyNTMsInN1YiI6MX0.ktkruy4A40A31CkrGFCjcAuIdS3nGK59V7NztiO_o2A

### Update enquiry
PUT https://sprinkles-of-joy-api.herokuapp.com/api/enquiries/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY5MTc2OTMsInN1YiI6MX0.20YATHVzO6uaJhy7cVRyjbV1L4H-xN_4Bjx0hojNuV8

{
    "name":"bob-update",
    "contact": "1235",
    "topic_id": 2,
    "message":"this is a test message 2"
}

### Delete method
DELETE https://sprinkles-of-joy-api.herokuapp.com/api/enquiries/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjY5MTc2OTMsInN1YiI6MX0.20YATHVzO6uaJhy7cVRyjbV1L4H-xN_4Bjx0hojNuV8

### USER METHODS

### User show  - profile or admin(all users)
GET https://sprinkles-of-joy-api.herokuapp.com/api/auth/user/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwMzk1NzMsInN1YiI6M30.pff91ACj6uwXFD-PSXJNNRt-07hv_AElhDbKlTdZcDc

### User update
PUT  https://sprinkles-of-joy-api.herokuapp.com/api/auth/update/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwMzk1NzMsInN1YiI6M30.pff91ACj6uwXFD-PSXJNNRt-07hv_AElhDbKlTdZcDc

{
    "username": "username12",
    "first_name": "first2",
    "middle_name": "middle2",
    "last_name": "last2", 
    "email": "email@12345.com",
    "password": "password12",
    "password_confirmation": "password12"
}

### User delete
DELETE https://sprinkles-of-joy-api.herokuapp.com/api/auth/delete/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwMzk1NzMsInN1YiI6M30.pff91ACj6uwXFD-PSXJNNRt-07hv_AElhDbKlTdZcDc

### Test site HTTP requests -----------------------------------------------------------

### Sign in user
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{ 
    "email": "test@test.com",
    "password": "password"
}

### Sign in user 2
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{ 
    "email": "test2@test2.com",
    "password": "password"
}

### Sign in user - admin
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{ 
    "email": "admin@admin.com",
    "password": "password"
}


### Sign in user - incorrect details
POST http://localhost:3000/api/auth/sign_in
Content-Type: application/json

{ 
    "email": "test123",
    "password": "passwo"
}

### Registarion method
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "username": "username1",
    "first_name": "first",
    "middle_name": "middle",
    "last_name": "last", 
    "email": "email2@email.com",
    "password": "123",
    "password_confirmation": "123",
    "admin": "false"
}

### Registarion method -fail (taken & wrong password) 
POST http://localhost:3000/api/auth/sign_up
Content-Type: application/json

{
    "username": "username",
    "first_name": "first",
    "middle_name": "middle",
    "last_name": "last", 
    "email": "email@email.com",
    "password": "password1",
    "password_confirmation": "password"
}

### get topics 
GET http://localhost:3000/api/topics

### get cakes
GET http://localhost:3000/api/cakes

### show cake
GET http://localhost:3000/api/cakes/2

### Index method - show all current user enquiries or admin (all enquiries)
GET http://localhost:3000/api/enquiries
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwNDYyNDgsInN1YiI6Mn0.Pypl7yQ2HplphI0DRau4SWFvbJl33CDu3LHHbJxHXQ4

### Creating an enquiry - Success 
POST http://localhost:3000/api/enquiries
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwNDYyMTIsInN1YiI6MX0.QOpPbjOZ6jwxsbFqrYmKAUBcjid_FN6TaxpWD7kUElM

{
    "name":"Test3",
    "contact": "0411123123",
    "topic_id": 3,
    "message":"message test"
}

### Creating an enquiry - fail 
POST http://localhost:3000/api/enquiries
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwNDYyMTIsInN1YiI6MX0.QOpPbjOZ6jwxsbFqrYmKAUBcjid_FN6TaxpWD7kUElM

{
    "name":"hi",
    "contact": 1234,
    "message":"hello"
}

### Show enquiry - success 
GET http://localhost:3000/api/enquiries/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwNDYyNDgsInN1YiI6Mn0.Pypl7yQ2HplphI0DRau4SWFvbJl33CDu3LHHbJxHXQ4
### Show enquiry - fail 
GET http://localhost:3000/api/enquiries/2000
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwNDYyNDgsInN1YiI6Mn0.Pypl7yQ2HplphI0DRau4SWFvbJl33CDu3LHHbJxHXQ4

### Update enquiry
PUT http://localhost:3000/api/enquiries/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwNDYyMTIsInN1YiI6MX0.QOpPbjOZ6jwxsbFqrYmKAUBcjid_FN6TaxpWD7kUElM

{
    "name":"bob-update",
    "contact": "1235",
    "topic_id": 2,
    "message":"this is a test message 2"
}

### Delete method
DELETE http://localhost:3000/api/enquiries/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwNDYyMTIsInN1YiI6MX0.QOpPbjOZ6jwxsbFqrYmKAUBcjid_FN6TaxpWD7kUElM

### USER METHODS

### User show  - profile or admin(all users)
GET http://localhost:3000/api/auth/user/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwNDYyNDgsInN1YiI6Mn0.Pypl7yQ2HplphI0DRau4SWFvbJl33CDu3LHHbJxHXQ4

### User update
PUT  http://localhost:3000/api/auth/update/2
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwNDYyNDgsInN1YiI6Mn0.Pypl7yQ2HplphI0DRau4SWFvbJl33CDu3LHHbJxHXQ4

{
    "username": "username12",
    "first_name": "first2",
    "middle_name": "middle2",
    "last_name": "last2", 
    "email": "email@12345.com",
    "password": "password12",
    "password_confirmation": "password12"
}

### User delete
DELETE http://localhost:3000/api/auth/delete/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjcwNDYyMTIsInN1YiI6MX0.QOpPbjOZ6jwxsbFqrYmKAUBcjid_FN6TaxpWD7kUElM